resolver 127.0.0.11 valid=10s;

server {
    listen 3000;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/node/ {
        set $node http://validator-1:26657;
        rewrite ^/api/node/(.*) /$1 break;
        proxy_pass $node;
    }

    location /api/indexer/ {
        set $idx http://indexer:26680;
        rewrite ^/api/indexer/(.*) /$1 break;
        proxy_pass $idx;
    }
}
