// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: consensus.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockProposal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *Block                 `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockProposal) Reset() {
	*x = BlockProposal{}
	mi := &file_consensus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockProposal) ProtoMessage() {}

func (x *BlockProposal) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockProposal.ProtoReflect.Descriptor instead.
func (*BlockProposal) Descriptor() ([]byte, []int) {
	return file_consensus_proto_rawDescGZIP(), []int{0}
}

func (x *BlockProposal) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

type FinalizedBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *Block                 `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Qc            *QuorumCertificate     `protobuf:"bytes,2,opt,name=qc,proto3" json:"qc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizedBlock) Reset() {
	*x = FinalizedBlock{}
	mi := &file_consensus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizedBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizedBlock) ProtoMessage() {}

func (x *FinalizedBlock) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizedBlock.ProtoReflect.Descriptor instead.
func (*FinalizedBlock) Descriptor() ([]byte, []int) {
	return file_consensus_proto_rawDescGZIP(), []int{1}
}

func (x *FinalizedBlock) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *FinalizedBlock) GetQc() *QuorumCertificate {
	if x != nil {
		return x.Qc
	}
	return nil
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromHeight    uint64                 `protobuf:"varint,1,opt,name=from_height,json=fromHeight,proto3" json:"from_height,omitempty"`
	ToHeight      uint64                 `protobuf:"varint,2,opt,name=to_height,json=toHeight,proto3" json:"to_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_consensus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_consensus_proto_rawDescGZIP(), []int{2}
}

func (x *SyncRequest) GetFromHeight() uint64 {
	if x != nil {
		return x.FromHeight
	}
	return 0
}

func (x *SyncRequest) GetToHeight() uint64 {
	if x != nil {
		return x.ToHeight
	}
	return 0
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*FinalizedBlock      `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_consensus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_consensus_proto_rawDescGZIP(), []int{3}
}

func (x *SyncResponse) GetBlocks() []*FinalizedBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type PeerStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Address         []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	LatestHeight    uint64                 `protobuf:"varint,2,opt,name=latest_height,json=latestHeight,proto3" json:"latest_height,omitempty"`
	LatestBlockHash []byte                 `protobuf:"bytes,3,opt,name=latest_block_hash,json=latestBlockHash,proto3" json:"latest_block_hash,omitempty"`
	ChainId         string                 `protobuf:"bytes,4,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PeerStatus) Reset() {
	*x = PeerStatus{}
	mi := &file_consensus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerStatus) ProtoMessage() {}

func (x *PeerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerStatus.ProtoReflect.Descriptor instead.
func (*PeerStatus) Descriptor() ([]byte, []int) {
	return file_consensus_proto_rawDescGZIP(), []int{4}
}

func (x *PeerStatus) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *PeerStatus) GetLatestHeight() uint64 {
	if x != nil {
		return x.LatestHeight
	}
	return 0
}

func (x *PeerStatus) GetLatestBlockHash() []byte {
	if x != nil {
		return x.LatestBlockHash
	}
	return nil
}

func (x *PeerStatus) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

type TxSubmission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tx            *Transaction           `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxSubmission) Reset() {
	*x = TxSubmission{}
	mi := &file_consensus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxSubmission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxSubmission) ProtoMessage() {}

func (x *TxSubmission) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxSubmission.ProtoReflect.Descriptor instead.
func (*TxSubmission) Descriptor() ([]byte, []int) {
	return file_consensus_proto_rawDescGZIP(), []int{5}
}

func (x *TxSubmission) GetTx() *Transaction {
	if x != nil {
		return x.Tx
	}
	return nil
}

type TxSubmissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxSubmissionResponse) Reset() {
	*x = TxSubmissionResponse{}
	mi := &file_consensus_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxSubmissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxSubmissionResponse) ProtoMessage() {}

func (x *TxSubmissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxSubmissionResponse.ProtoReflect.Descriptor instead.
func (*TxSubmissionResponse) Descriptor() ([]byte, []int) {
	return file_consensus_proto_rawDescGZIP(), []int{6}
}

func (x *TxSubmissionResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *TxSubmissionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PeerExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderAddr    string                 `protobuf:"bytes,1,opt,name=sender_addr,json=senderAddr,proto3" json:"sender_addr,omitempty"` // the requester's listen address
	KnownPeers    []string               `protobuf:"bytes,2,rep,name=known_peers,json=knownPeers,proto3" json:"known_peers,omitempty"` // peers the requester already knows
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerExchangeRequest) Reset() {
	*x = PeerExchangeRequest{}
	mi := &file_consensus_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerExchangeRequest) ProtoMessage() {}

func (x *PeerExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerExchangeRequest.ProtoReflect.Descriptor instead.
func (*PeerExchangeRequest) Descriptor() ([]byte, []int) {
	return file_consensus_proto_rawDescGZIP(), []int{7}
}

func (x *PeerExchangeRequest) GetSenderAddr() string {
	if x != nil {
		return x.SenderAddr
	}
	return ""
}

func (x *PeerExchangeRequest) GetKnownPeers() []string {
	if x != nil {
		return x.KnownPeers
	}
	return nil
}

type PeerExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []string               `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"` // peers the responder knows
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerExchangeResponse) Reset() {
	*x = PeerExchangeResponse{}
	mi := &file_consensus_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerExchangeResponse) ProtoMessage() {}

func (x *PeerExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerExchangeResponse.ProtoReflect.Descriptor instead.
func (*PeerExchangeResponse) Descriptor() ([]byte, []int) {
	return file_consensus_proto_rawDescGZIP(), []int{8}
}

func (x *PeerExchangeResponse) GetPeers() []string {
	if x != nil {
		return x.Peers
	}
	return nil
}

var File_consensus_proto protoreflect.FileDescriptor

const file_consensus_proto_rawDesc = "" +
	"\n" +
	"\x0fconsensus.proto\x12\bdrana.v1\x1a\vtypes.proto\"6\n" +
	"\rBlockProposal\x12%\n" +
	"\x05block\x18\x01 \x01(\v2\x0f.drana.v1.BlockR\x05block\"d\n" +
	"\x0eFinalizedBlock\x12%\n" +
	"\x05block\x18\x01 \x01(\v2\x0f.drana.v1.BlockR\x05block\x12+\n" +
	"\x02qc\x18\x02 \x01(\v2\x1b.drana.v1.QuorumCertificateR\x02qc\"K\n" +
	"\vSyncRequest\x12\x1f\n" +
	"\vfrom_height\x18\x01 \x01(\x04R\n" +
	"fromHeight\x12\x1b\n" +
	"\tto_height\x18\x02 \x01(\x04R\btoHeight\"@\n" +
	"\fSyncResponse\x120\n" +
	"\x06blocks\x18\x01 \x03(\v2\x18.drana.v1.FinalizedBlockR\x06blocks\"\x92\x01\n" +
	"\n" +
	"PeerStatus\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12#\n" +
	"\rlatest_height\x18\x02 \x01(\x04R\flatestHeight\x12*\n" +
	"\x11latest_block_hash\x18\x03 \x01(\fR\x0flatestBlockHash\x12\x19\n" +
	"\bchain_id\x18\x04 \x01(\tR\achainId\"5\n" +
	"\fTxSubmission\x12%\n" +
	"\x02tx\x18\x01 \x01(\v2\x15.drana.v1.TransactionR\x02tx\"H\n" +
	"\x14TxSubmissionResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"W\n" +
	"\x13PeerExchangeRequest\x12\x1f\n" +
	"\vsender_addr\x18\x01 \x01(\tR\n" +
	"senderAddr\x12\x1f\n" +
	"\vknown_peers\x18\x02 \x03(\tR\n" +
	"knownPeers\",\n" +
	"\x14PeerExchangeResponse\x12\x14\n" +
	"\x05peers\x18\x01 \x03(\tR\x05peers2\xa2\x03\n" +
	"\x10ConsensusService\x12<\n" +
	"\fProposeBlock\x12\x17.drana.v1.BlockProposal\x1a\x13.drana.v1.BlockVote\x12F\n" +
	"\x14NotifyFinalizedBlock\x12\x18.drana.v1.FinalizedBlock\x1a\x14.drana.v1.PeerStatus\x12;\n" +
	"\n" +
	"SyncBlocks\x12\x15.drana.v1.SyncRequest\x1a\x16.drana.v1.SyncResponse\x127\n" +
	"\tGetStatus\x12\x14.drana.v1.PeerStatus\x1a\x14.drana.v1.PeerStatus\x12B\n" +
	"\bSubmitTx\x12\x16.drana.v1.TxSubmission\x1a\x1e.drana.v1.TxSubmissionResponse\x12N\n" +
	"\rExchangePeers\x12\x1d.drana.v1.PeerExchangeRequest\x1a\x1e.drana.v1.PeerExchangeResponseB0Z.github.com/drana-chain/drana/internal/proto/pbb\x06proto3"

var (
	file_consensus_proto_rawDescOnce sync.Once
	file_consensus_proto_rawDescData []byte
)

func file_consensus_proto_rawDescGZIP() []byte {
	file_consensus_proto_rawDescOnce.Do(func() {
		file_consensus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_consensus_proto_rawDesc), len(file_consensus_proto_rawDesc)))
	})
	return file_consensus_proto_rawDescData
}

var file_consensus_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_consensus_proto_goTypes = []any{
	(*BlockProposal)(nil),        // 0: drana.v1.BlockProposal
	(*FinalizedBlock)(nil),       // 1: drana.v1.FinalizedBlock
	(*SyncRequest)(nil),          // 2: drana.v1.SyncRequest
	(*SyncResponse)(nil),         // 3: drana.v1.SyncResponse
	(*PeerStatus)(nil),           // 4: drana.v1.PeerStatus
	(*TxSubmission)(nil),         // 5: drana.v1.TxSubmission
	(*TxSubmissionResponse)(nil), // 6: drana.v1.TxSubmissionResponse
	(*PeerExchangeRequest)(nil),  // 7: drana.v1.PeerExchangeRequest
	(*PeerExchangeResponse)(nil), // 8: drana.v1.PeerExchangeResponse
	(*Block)(nil),                // 9: drana.v1.Block
	(*QuorumCertificate)(nil),    // 10: drana.v1.QuorumCertificate
	(*Transaction)(nil),          // 11: drana.v1.Transaction
	(*BlockVote)(nil),            // 12: drana.v1.BlockVote
}
var file_consensus_proto_depIdxs = []int32{
	9,  // 0: drana.v1.BlockProposal.block:type_name -> drana.v1.Block
	9,  // 1: drana.v1.FinalizedBlock.block:type_name -> drana.v1.Block
	10, // 2: drana.v1.FinalizedBlock.qc:type_name -> drana.v1.QuorumCertificate
	1,  // 3: drana.v1.SyncResponse.blocks:type_name -> drana.v1.FinalizedBlock
	11, // 4: drana.v1.TxSubmission.tx:type_name -> drana.v1.Transaction
	0,  // 5: drana.v1.ConsensusService.ProposeBlock:input_type -> drana.v1.BlockProposal
	1,  // 6: drana.v1.ConsensusService.NotifyFinalizedBlock:input_type -> drana.v1.FinalizedBlock
	2,  // 7: drana.v1.ConsensusService.SyncBlocks:input_type -> drana.v1.SyncRequest
	4,  // 8: drana.v1.ConsensusService.GetStatus:input_type -> drana.v1.PeerStatus
	5,  // 9: drana.v1.ConsensusService.SubmitTx:input_type -> drana.v1.TxSubmission
	7,  // 10: drana.v1.ConsensusService.ExchangePeers:input_type -> drana.v1.PeerExchangeRequest
	12, // 11: drana.v1.ConsensusService.ProposeBlock:output_type -> drana.v1.BlockVote
	4,  // 12: drana.v1.ConsensusService.NotifyFinalizedBlock:output_type -> drana.v1.PeerStatus
	3,  // 13: drana.v1.ConsensusService.SyncBlocks:output_type -> drana.v1.SyncResponse
	4,  // 14: drana.v1.ConsensusService.GetStatus:output_type -> drana.v1.PeerStatus
	6,  // 15: drana.v1.ConsensusService.SubmitTx:output_type -> drana.v1.TxSubmissionResponse
	8,  // 16: drana.v1.ConsensusService.ExchangePeers:output_type -> drana.v1.PeerExchangeResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_consensus_proto_init() }
func file_consensus_proto_init() {
	if File_consensus_proto != nil {
		return
	}
	file_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_consensus_proto_rawDesc), len(file_consensus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_consensus_proto_goTypes,
		DependencyIndexes: file_consensus_proto_depIdxs,
		MessageInfos:      file_consensus_proto_msgTypes,
	}.Build()
	File_consensus_proto = out.File
	file_consensus_proto_goTypes = nil
	file_consensus_proto_depIdxs = nil
}
