// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.3
// source: consensus.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConsensusService_ProposeBlock_FullMethodName         = "/drana.v1.ConsensusService/ProposeBlock"
	ConsensusService_NotifyFinalizedBlock_FullMethodName = "/drana.v1.ConsensusService/NotifyFinalizedBlock"
	ConsensusService_SyncBlocks_FullMethodName           = "/drana.v1.ConsensusService/SyncBlocks"
	ConsensusService_GetStatus_FullMethodName            = "/drana.v1.ConsensusService/GetStatus"
	ConsensusService_SubmitTx_FullMethodName             = "/drana.v1.ConsensusService/SubmitTx"
	ConsensusService_ExchangePeers_FullMethodName        = "/drana.v1.ConsensusService/ExchangePeers"
)

// ConsensusServiceClient is the client API for ConsensusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConsensusServiceClient interface {
	ProposeBlock(ctx context.Context, in *BlockProposal, opts ...grpc.CallOption) (*BlockVote, error)
	NotifyFinalizedBlock(ctx context.Context, in *FinalizedBlock, opts ...grpc.CallOption) (*PeerStatus, error)
	SyncBlocks(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	GetStatus(ctx context.Context, in *PeerStatus, opts ...grpc.CallOption) (*PeerStatus, error)
	SubmitTx(ctx context.Context, in *TxSubmission, opts ...grpc.CallOption) (*TxSubmissionResponse, error)
	ExchangePeers(ctx context.Context, in *PeerExchangeRequest, opts ...grpc.CallOption) (*PeerExchangeResponse, error)
}

type consensusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConsensusServiceClient(cc grpc.ClientConnInterface) ConsensusServiceClient {
	return &consensusServiceClient{cc}
}

func (c *consensusServiceClient) ProposeBlock(ctx context.Context, in *BlockProposal, opts ...grpc.CallOption) (*BlockVote, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockVote)
	err := c.cc.Invoke(ctx, ConsensusService_ProposeBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consensusServiceClient) NotifyFinalizedBlock(ctx context.Context, in *FinalizedBlock, opts ...grpc.CallOption) (*PeerStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerStatus)
	err := c.cc.Invoke(ctx, ConsensusService_NotifyFinalizedBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consensusServiceClient) SyncBlocks(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, ConsensusService_SyncBlocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consensusServiceClient) GetStatus(ctx context.Context, in *PeerStatus, opts ...grpc.CallOption) (*PeerStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerStatus)
	err := c.cc.Invoke(ctx, ConsensusService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consensusServiceClient) SubmitTx(ctx context.Context, in *TxSubmission, opts ...grpc.CallOption) (*TxSubmissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TxSubmissionResponse)
	err := c.cc.Invoke(ctx, ConsensusService_SubmitTx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consensusServiceClient) ExchangePeers(ctx context.Context, in *PeerExchangeRequest, opts ...grpc.CallOption) (*PeerExchangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerExchangeResponse)
	err := c.cc.Invoke(ctx, ConsensusService_ExchangePeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsensusServiceServer is the server API for ConsensusService service.
// All implementations must embed UnimplementedConsensusServiceServer
// for forward compatibility.
type ConsensusServiceServer interface {
	ProposeBlock(context.Context, *BlockProposal) (*BlockVote, error)
	NotifyFinalizedBlock(context.Context, *FinalizedBlock) (*PeerStatus, error)
	SyncBlocks(context.Context, *SyncRequest) (*SyncResponse, error)
	GetStatus(context.Context, *PeerStatus) (*PeerStatus, error)
	SubmitTx(context.Context, *TxSubmission) (*TxSubmissionResponse, error)
	ExchangePeers(context.Context, *PeerExchangeRequest) (*PeerExchangeResponse, error)
	mustEmbedUnimplementedConsensusServiceServer()
}

// UnimplementedConsensusServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConsensusServiceServer struct{}

func (UnimplementedConsensusServiceServer) ProposeBlock(context.Context, *BlockProposal) (*BlockVote, error) {
	return nil, status.Error(codes.Unimplemented, "method ProposeBlock not implemented")
}
func (UnimplementedConsensusServiceServer) NotifyFinalizedBlock(context.Context, *FinalizedBlock) (*PeerStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyFinalizedBlock not implemented")
}
func (UnimplementedConsensusServiceServer) SyncBlocks(context.Context, *SyncRequest) (*SyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncBlocks not implemented")
}
func (UnimplementedConsensusServiceServer) GetStatus(context.Context, *PeerStatus) (*PeerStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedConsensusServiceServer) SubmitTx(context.Context, *TxSubmission) (*TxSubmissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTx not implemented")
}
func (UnimplementedConsensusServiceServer) ExchangePeers(context.Context, *PeerExchangeRequest) (*PeerExchangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangePeers not implemented")
}
func (UnimplementedConsensusServiceServer) mustEmbedUnimplementedConsensusServiceServer() {}
func (UnimplementedConsensusServiceServer) testEmbeddedByValue()                          {}

// UnsafeConsensusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsensusServiceServer will
// result in compilation errors.
type UnsafeConsensusServiceServer interface {
	mustEmbedUnimplementedConsensusServiceServer()
}

func RegisterConsensusServiceServer(s grpc.ServiceRegistrar, srv ConsensusServiceServer) {
	// If the following call panics, it indicates UnimplementedConsensusServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConsensusService_ServiceDesc, srv)
}

func _ConsensusService_ProposeBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockProposal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsensusServiceServer).ProposeBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsensusService_ProposeBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsensusServiceServer).ProposeBlock(ctx, req.(*BlockProposal))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsensusService_NotifyFinalizedBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizedBlock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsensusServiceServer).NotifyFinalizedBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsensusService_NotifyFinalizedBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsensusServiceServer).NotifyFinalizedBlock(ctx, req.(*FinalizedBlock))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsensusService_SyncBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsensusServiceServer).SyncBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsensusService_SyncBlocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsensusServiceServer).SyncBlocks(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsensusService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsensusServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsensusService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsensusServiceServer).GetStatus(ctx, req.(*PeerStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsensusService_SubmitTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxSubmission)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsensusServiceServer).SubmitTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsensusService_SubmitTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsensusServiceServer).SubmitTx(ctx, req.(*TxSubmission))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsensusService_ExchangePeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsensusServiceServer).ExchangePeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsensusService_ExchangePeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsensusServiceServer).ExchangePeers(ctx, req.(*PeerExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConsensusService_ServiceDesc is the grpc.ServiceDesc for ConsensusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConsensusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drana.v1.ConsensusService",
	HandlerType: (*ConsensusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProposeBlock",
			Handler:    _ConsensusService_ProposeBlock_Handler,
		},
		{
			MethodName: "NotifyFinalizedBlock",
			Handler:    _ConsensusService_NotifyFinalizedBlock_Handler,
		},
		{
			MethodName: "SyncBlocks",
			Handler:    _ConsensusService_SyncBlocks_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _ConsensusService_GetStatus_Handler,
		},
		{
			MethodName: "SubmitTx",
			Handler:    _ConsensusService_SubmitTx_Handler,
		},
		{
			MethodName: "ExchangePeers",
			Handler:    _ConsensusService_ExchangePeers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "consensus.proto",
}
