// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: types.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Balance       uint64                 `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Nonce         uint64                 `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Account) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Account) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Post struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PostId          []byte                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Author          []byte                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Text            string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAtHeight uint64                 `protobuf:"varint,4,opt,name=created_at_height,json=createdAtHeight,proto3" json:"created_at_height,omitempty"`
	CreatedAtTime   int64                  `protobuf:"varint,5,opt,name=created_at_time,json=createdAtTime,proto3" json:"created_at_time,omitempty"`
	TotalCommitted  uint64                 `protobuf:"varint,6,opt,name=total_committed,json=totalCommitted,proto3" json:"total_committed,omitempty"`
	BoostCount      uint64                 `protobuf:"varint,7,opt,name=boost_count,json=boostCount,proto3" json:"boost_count,omitempty"`
	Channel         string                 `protobuf:"bytes,8,opt,name=channel,proto3" json:"channel,omitempty"`
	ParentPostId    []byte                 `protobuf:"bytes,9,opt,name=parent_post_id,json=parentPostId,proto3" json:"parent_post_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

func (x *Post) GetPostId() []byte {
	if x != nil {
		return x.PostId
	}
	return nil
}

func (x *Post) GetAuthor() []byte {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Post) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Post) GetCreatedAtHeight() uint64 {
	if x != nil {
		return x.CreatedAtHeight
	}
	return 0
}

func (x *Post) GetCreatedAtTime() int64 {
	if x != nil {
		return x.CreatedAtTime
	}
	return 0
}

func (x *Post) GetTotalCommitted() uint64 {
	if x != nil {
		return x.TotalCommitted
	}
	return 0
}

func (x *Post) GetBoostCount() uint64 {
	if x != nil {
		return x.BoostCount
	}
	return 0
}

func (x *Post) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Post) GetParentPostId() []byte {
	if x != nil {
		return x.ParentPostId
	}
	return nil
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Sender        []byte                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient     []byte                 `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	PostId        []byte                 `protobuf:"bytes,4,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	Amount        uint64                 `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Nonce         uint64                 `protobuf:"varint,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Signature     []byte                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	PubKey        []byte                 `protobuf:"bytes,9,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Channel       string                 `protobuf:"bytes,10,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Transaction) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *Transaction) GetRecipient() []byte {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *Transaction) GetPostId() []byte {
	if x != nil {
		return x.PostId
	}
	return nil
}

func (x *Transaction) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Transaction) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Transaction) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Transaction) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *Transaction) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type BlockHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	PrevHash      []byte                 `protobuf:"bytes,2,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	ProposerAddr  []byte                 `protobuf:"bytes,3,opt,name=proposer_addr,json=proposerAddr,proto3" json:"proposer_addr,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	StateRoot     []byte                 `protobuf:"bytes,5,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	TxRoot        []byte                 `protobuf:"bytes,6,opt,name=tx_root,json=txRoot,proto3" json:"tx_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockHeader) Reset() {
	*x = BlockHeader{}
	mi := &file_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeader) ProtoMessage() {}

func (x *BlockHeader) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeader.ProtoReflect.Descriptor instead.
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{3}
}

func (x *BlockHeader) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockHeader) GetPrevHash() []byte {
	if x != nil {
		return x.PrevHash
	}
	return nil
}

func (x *BlockHeader) GetProposerAddr() []byte {
	if x != nil {
		return x.ProposerAddr
	}
	return nil
}

func (x *BlockHeader) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BlockHeader) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *BlockHeader) GetTxRoot() []byte {
	if x != nil {
		return x.TxRoot
	}
	return nil
}

type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *BlockHeader           `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Transactions  []*Transaction         `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Qc            *QuorumCertificate     `protobuf:"bytes,3,opt,name=qc,proto3" json:"qc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{4}
}

func (x *Block) GetHeader() *BlockHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Block) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *Block) GetQc() *QuorumCertificate {
	if x != nil {
		return x.Qc
	}
	return nil
}

type BlockVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	BlockHash     []byte                 `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	VoterAddress  []byte                 `protobuf:"bytes,3,opt,name=voter_address,json=voterAddress,proto3" json:"voter_address,omitempty"`
	VoterPubKey   []byte                 `protobuf:"bytes,4,opt,name=voter_pub_key,json=voterPubKey,proto3" json:"voter_pub_key,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockVote) Reset() {
	*x = BlockVote{}
	mi := &file_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockVote) ProtoMessage() {}

func (x *BlockVote) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockVote.ProtoReflect.Descriptor instead.
func (*BlockVote) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{5}
}

func (x *BlockVote) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockVote) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *BlockVote) GetVoterAddress() []byte {
	if x != nil {
		return x.VoterAddress
	}
	return nil
}

func (x *BlockVote) GetVoterPubKey() []byte {
	if x != nil {
		return x.VoterPubKey
	}
	return nil
}

func (x *BlockVote) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type QuorumCertificate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	BlockHash     []byte                 `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Votes         []*BlockVote           `protobuf:"bytes,3,rep,name=votes,proto3" json:"votes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuorumCertificate) Reset() {
	*x = QuorumCertificate{}
	mi := &file_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuorumCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumCertificate) ProtoMessage() {}

func (x *QuorumCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuorumCertificate.ProtoReflect.Descriptor instead.
func (*QuorumCertificate) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{6}
}

func (x *QuorumCertificate) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *QuorumCertificate) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *QuorumCertificate) GetVotes() []*BlockVote {
	if x != nil {
		return x.Votes
	}
	return nil
}

type GenesisConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ChainId            string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	GenesisTime        int64                  `protobuf:"varint,2,opt,name=genesis_time,json=genesisTime,proto3" json:"genesis_time,omitempty"`
	Accounts           []*GenesisAccount      `protobuf:"bytes,3,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Validators         []*GenesisValidator    `protobuf:"bytes,4,rep,name=validators,proto3" json:"validators,omitempty"`
	MaxPostLength      int32                  `protobuf:"varint,5,opt,name=max_post_length,json=maxPostLength,proto3" json:"max_post_length,omitempty"`
	MaxPostBytes       int32                  `protobuf:"varint,6,opt,name=max_post_bytes,json=maxPostBytes,proto3" json:"max_post_bytes,omitempty"`
	MinPostCommitment  uint64                 `protobuf:"varint,7,opt,name=min_post_commitment,json=minPostCommitment,proto3" json:"min_post_commitment,omitempty"`
	MinBoostCommitment uint64                 `protobuf:"varint,8,opt,name=min_boost_commitment,json=minBoostCommitment,proto3" json:"min_boost_commitment,omitempty"`
	MaxTxPerBlock      int32                  `protobuf:"varint,9,opt,name=max_tx_per_block,json=maxTxPerBlock,proto3" json:"max_tx_per_block,omitempty"`
	MaxBlockBytes      int32                  `protobuf:"varint,10,opt,name=max_block_bytes,json=maxBlockBytes,proto3" json:"max_block_bytes,omitempty"`
	BlockIntervalSec   int32                  `protobuf:"varint,11,opt,name=block_interval_sec,json=blockIntervalSec,proto3" json:"block_interval_sec,omitempty"`
	BlockReward        uint64                 `protobuf:"varint,12,opt,name=block_reward,json=blockReward,proto3" json:"block_reward,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GenesisConfig) Reset() {
	*x = GenesisConfig{}
	mi := &file_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisConfig) ProtoMessage() {}

func (x *GenesisConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisConfig.ProtoReflect.Descriptor instead.
func (*GenesisConfig) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{7}
}

func (x *GenesisConfig) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *GenesisConfig) GetGenesisTime() int64 {
	if x != nil {
		return x.GenesisTime
	}
	return 0
}

func (x *GenesisConfig) GetAccounts() []*GenesisAccount {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *GenesisConfig) GetValidators() []*GenesisValidator {
	if x != nil {
		return x.Validators
	}
	return nil
}

func (x *GenesisConfig) GetMaxPostLength() int32 {
	if x != nil {
		return x.MaxPostLength
	}
	return 0
}

func (x *GenesisConfig) GetMaxPostBytes() int32 {
	if x != nil {
		return x.MaxPostBytes
	}
	return 0
}

func (x *GenesisConfig) GetMinPostCommitment() uint64 {
	if x != nil {
		return x.MinPostCommitment
	}
	return 0
}

func (x *GenesisConfig) GetMinBoostCommitment() uint64 {
	if x != nil {
		return x.MinBoostCommitment
	}
	return 0
}

func (x *GenesisConfig) GetMaxTxPerBlock() int32 {
	if x != nil {
		return x.MaxTxPerBlock
	}
	return 0
}

func (x *GenesisConfig) GetMaxBlockBytes() int32 {
	if x != nil {
		return x.MaxBlockBytes
	}
	return 0
}

func (x *GenesisConfig) GetBlockIntervalSec() int32 {
	if x != nil {
		return x.BlockIntervalSec
	}
	return 0
}

func (x *GenesisConfig) GetBlockReward() uint64 {
	if x != nil {
		return x.BlockReward
	}
	return 0
}

type GenesisAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Balance       uint64                 `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenesisAccount) Reset() {
	*x = GenesisAccount{}
	mi := &file_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisAccount) ProtoMessage() {}

func (x *GenesisAccount) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisAccount.ProtoReflect.Descriptor instead.
func (*GenesisAccount) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{8}
}

func (x *GenesisAccount) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *GenesisAccount) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type GenesisValidator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PubKey        []byte                 `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenesisValidator) Reset() {
	*x = GenesisValidator{}
	mi := &file_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisValidator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisValidator) ProtoMessage() {}

func (x *GenesisValidator) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisValidator.ProtoReflect.Descriptor instead.
func (*GenesisValidator) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{9}
}

func (x *GenesisValidator) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *GenesisValidator) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *GenesisValidator) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_types_proto protoreflect.FileDescriptor

const file_types_proto_rawDesc = "" +
	"\n" +
	"\vtypes.proto\x12\bdrana.v1\"g\n" +
	"\aAccount\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x04R\abalance\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\x04R\x05nonce\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"\xa9\x02\n" +
	"\x04Post\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\fR\x06postId\x12\x16\n" +
	"\x06author\x18\x02 \x01(\fR\x06author\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12*\n" +
	"\x11created_at_height\x18\x04 \x01(\x04R\x0fcreatedAtHeight\x12&\n" +
	"\x0fcreated_at_time\x18\x05 \x01(\x03R\rcreatedAtTime\x12'\n" +
	"\x0ftotal_committed\x18\x06 \x01(\x04R\x0etotalCommitted\x12\x1f\n" +
	"\vboost_count\x18\a \x01(\x04R\n" +
	"boostCount\x12\x18\n" +
	"\achannel\x18\b \x01(\tR\achannel\x12$\n" +
	"\x0eparent_post_id\x18\t \x01(\fR\fparentPostId\"\x83\x02\n" +
	"\vTransaction\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\fR\x06sender\x12\x1c\n" +
	"\trecipient\x18\x03 \x01(\fR\trecipient\x12\x17\n" +
	"\apost_id\x18\x04 \x01(\fR\x06postId\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x04R\x06amount\x12\x14\n" +
	"\x05nonce\x18\a \x01(\x04R\x05nonce\x12\x1c\n" +
	"\tsignature\x18\b \x01(\fR\tsignature\x12\x17\n" +
	"\apub_key\x18\t \x01(\fR\x06pubKey\x12\x18\n" +
	"\achannel\x18\n" +
	" \x01(\tR\achannel\"\xbd\x01\n" +
	"\vBlockHeader\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x1b\n" +
	"\tprev_hash\x18\x02 \x01(\fR\bprevHash\x12#\n" +
	"\rproposer_addr\x18\x03 \x01(\fR\fproposerAddr\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"state_root\x18\x05 \x01(\fR\tstateRoot\x12\x17\n" +
	"\atx_root\x18\x06 \x01(\fR\x06txRoot\"\x9e\x01\n" +
	"\x05Block\x12-\n" +
	"\x06header\x18\x01 \x01(\v2\x15.drana.v1.BlockHeaderR\x06header\x129\n" +
	"\ftransactions\x18\x02 \x03(\v2\x15.drana.v1.TransactionR\ftransactions\x12+\n" +
	"\x02qc\x18\x03 \x01(\v2\x1b.drana.v1.QuorumCertificateR\x02qc\"\xa9\x01\n" +
	"\tBlockVote\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\fR\tblockHash\x12#\n" +
	"\rvoter_address\x18\x03 \x01(\fR\fvoterAddress\x12\"\n" +
	"\rvoter_pub_key\x18\x04 \x01(\fR\vvoterPubKey\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"u\n" +
	"\x11QuorumCertificate\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\fR\tblockHash\x12)\n" +
	"\x05votes\x18\x03 \x03(\v2\x13.drana.v1.BlockVoteR\x05votes\"\x91\x04\n" +
	"\rGenesisConfig\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12!\n" +
	"\fgenesis_time\x18\x02 \x01(\x03R\vgenesisTime\x124\n" +
	"\baccounts\x18\x03 \x03(\v2\x18.drana.v1.GenesisAccountR\baccounts\x12:\n" +
	"\n" +
	"validators\x18\x04 \x03(\v2\x1a.drana.v1.GenesisValidatorR\n" +
	"validators\x12&\n" +
	"\x0fmax_post_length\x18\x05 \x01(\x05R\rmaxPostLength\x12$\n" +
	"\x0emax_post_bytes\x18\x06 \x01(\x05R\fmaxPostBytes\x12.\n" +
	"\x13min_post_commitment\x18\a \x01(\x04R\x11minPostCommitment\x120\n" +
	"\x14min_boost_commitment\x18\b \x01(\x04R\x12minBoostCommitment\x12'\n" +
	"\x10max_tx_per_block\x18\t \x01(\x05R\rmaxTxPerBlock\x12&\n" +
	"\x0fmax_block_bytes\x18\n" +
	" \x01(\x05R\rmaxBlockBytes\x12,\n" +
	"\x12block_interval_sec\x18\v \x01(\x05R\x10blockIntervalSec\x12!\n" +
	"\fblock_reward\x18\f \x01(\x04R\vblockReward\"D\n" +
	"\x0eGenesisAccount\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x04R\abalance\"Y\n" +
	"\x10GenesisValidator\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x17\n" +
	"\apub_key\x18\x02 \x01(\fR\x06pubKey\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04nameB0Z.github.com/drana-chain/drana/internal/proto/pbb\x06proto3"

var (
	file_types_proto_rawDescOnce sync.Once
	file_types_proto_rawDescData []byte
)

func file_types_proto_rawDescGZIP() []byte {
	file_types_proto_rawDescOnce.Do(func() {
		file_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)))
	})
	return file_types_proto_rawDescData
}

var file_types_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_types_proto_goTypes = []any{
	(*Account)(nil),           // 0: drana.v1.Account
	(*Post)(nil),              // 1: drana.v1.Post
	(*Transaction)(nil),       // 2: drana.v1.Transaction
	(*BlockHeader)(nil),       // 3: drana.v1.BlockHeader
	(*Block)(nil),             // 4: drana.v1.Block
	(*BlockVote)(nil),         // 5: drana.v1.BlockVote
	(*QuorumCertificate)(nil), // 6: drana.v1.QuorumCertificate
	(*GenesisConfig)(nil),     // 7: drana.v1.GenesisConfig
	(*GenesisAccount)(nil),    // 8: drana.v1.GenesisAccount
	(*GenesisValidator)(nil),  // 9: drana.v1.GenesisValidator
}
var file_types_proto_depIdxs = []int32{
	3, // 0: drana.v1.Block.header:type_name -> drana.v1.BlockHeader
	2, // 1: drana.v1.Block.transactions:type_name -> drana.v1.Transaction
	6, // 2: drana.v1.Block.qc:type_name -> drana.v1.QuorumCertificate
	5, // 3: drana.v1.QuorumCertificate.votes:type_name -> drana.v1.BlockVote
	8, // 4: drana.v1.GenesisConfig.accounts:type_name -> drana.v1.GenesisAccount
	9, // 5: drana.v1.GenesisConfig.validators:type_name -> drana.v1.GenesisValidator
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_types_proto_init() }
func file_types_proto_init() {
	if File_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_proto_goTypes,
		DependencyIndexes: file_types_proto_depIdxs,
		MessageInfos:      file_types_proto_msgTypes,
	}.Build()
	File_types_proto = out.File
	file_types_proto_goTypes = nil
	file_types_proto_depIdxs = nil
}
